uploads = []
outputs = []

[[generated]]
id = "IVtAY3H-yeh6R-QBbovNQ"
uri = "file://artifacts/reclaim-yourself/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "E5BzoI9yDosfvBwd8bl52"
uri = "file://artifacts/reclaim-yourself/assets/images/splash.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qXsBPa9iI15U6HhdlGEBw"
uri = "file://artifacts/reclaim-yourself/assets/images/hero-card.png"
type = "image"
title = "generated_image"
