export interface Card {
  id: string;
  title: string;
  theme: string;
  message: string;
  prompt: string;
  reflection: string;
  practice: string;
  affirmation: string;
}

export const CARDS: Card[] = [
  {
    id: "1",
    title: "Soften",
    theme: "Surrender & Release",
    message: "You don't have to hold it all together. The bravest thing you can do today is let something be imperfect... and love yourself through it.",
    prompt: "Where are you gripping too tightly?",
    reflection: "What would it feel like to exhale fully and trust that you are enough exactly as you are right now?",
    practice: "Place one hand on your heart. Take three slow breaths and whisper: 'I don't have to earn my rest.'",
    affirmation: "I release what no longer serves me and make room for what is meant for me.",
  },
  {
    id: "2",
    title: "Return",
    theme: "Coming Home",
    message: "Every time you've left yourself... for approval, for love, for belonging... this card is the doorway back. You were never lost. You were on your way home.",
    prompt: "What does it mean to come home to yourself?",
    reflection: "In what moments do you feel most like yourself? What conditions made that possible?",
    practice: "Sit quietly for five minutes. Notice what you feel without trying to change it. That noticing is the return.",
    affirmation: "I am always finding my way back to myself.",
  },
  {
    id: "3",
    title: "Worthy",
    theme: "Belonging & Enoughness",
    message: "Your worth was never something you could earn. It was never conditional on how much you gave, how thin you were, how agreeable you stayed. It was always already yours.",
    prompt: "What would you do if you knew you were already enough?",
    reflection: "Whose voice taught you that you had to earn your place? Is that voice your truth ... or was it someone else's fear?",
    practice: "Write down three things you would allow yourself if you believed you were unconditionally worthy.",
    affirmation: "My worth is not negotiable. I am enough.",
  },
  {
    id: "4",
    title: "Rest",
    theme: "Restoration",
    message: "Rest is not a reward for finishing. It is how you remember that you are more than what you produce. You are allowed to simply be.",
    prompt: "What does real rest feel like for you?",
    reflection: "Do you carry guilt when you rest? Where did that guilt come from, and is it serving you?",
    practice: "Do one thing today that has no productive purpose. Let it be enough.",
    affirmation: "My rest is holy. I honour my need for stillness.",
  },
  {
    id: "5",
    title: "Voice",
    theme: "Reclaiming Your Truth",
    message: "Somewhere along the way you learned that staying quiet was safer. This card asks you to gently, courageously begin to speak ... even if your voice shakes.",
    prompt: "What truth have you been afraid to speak?",
    reflection: "Who in your life makes you feel fully heard? What makes that different from other relationships?",
    practice: "Say one honest thing today that you would normally swallow. Even to yourself in the mirror.",
    affirmation: "My voice matters. I speak my truth with gentleness and courage.",
  },
  {
    id: "6",
    title: "Boundary",
    theme: "Sacred No",
    message: "A boundary is not a wall. It is an act of love ... for yourself, and for the relationship. Every honest no makes space for a truer yes.",
    prompt: "Where do you need a boundary that love has made difficult?",
    reflection: "How do you feel when you say yes but mean no? What does that cost you over time?",
    practice: "Identify one boundary you've been avoiding. Write it down. You don't have to act on it today ... just name it.",
    affirmation: "My boundaries are an act of self-respect and love.",
  },
  {
    id: "7",
    title: "Grief",
    theme: "Honoring Loss",
    message: "Grief is not a problem to be solved. It is love with nowhere to go. Let it be here. Let it be witnessed. This is how you honor what mattered.",
    prompt: "What are you grieving that you haven't let yourself name?",
    reflection: "Is there a loss ... a person, a version of yourself, a dream ... that you haven't yet allowed yourself to mourn?",
    practice: "Light a candle. Name what you are grieving out loud, or in writing. Let yourself feel it for five minutes without rushing to fix it.",
    affirmation: "My grief is sacred. I give it the space it deserves.",
  },
  {
    id: "8",
    title: "Desire",
    theme: "Reclaiming Want",
    message: "You were taught to want less, need less, take up less. This card gives you permission to want something ... boldly, honestly, without apology.",
    prompt: "What do you truly want that you've been afraid to admit?",
    reflection: "What desires have you abandoned because they seemed too much, too selfish, too impossible?",
    practice: "Write a list of ten things you want. Don't edit. Don't explain. Just want.",
    affirmation: "My desires are valid. I am allowed to want beautiful things.",
  },
  {
    id: "9",
    title: "Patience",
    theme: "Divine Timing",
    message: "The seed does not bloom on demand. Your becoming has its own season. Trust the timing of your life even when you cannot see the roots growing.",
    prompt: "Where are you rushing something that needs more time?",
    reflection: "What would shift if you believed that where you are right now is exactly where you need to be?",
    practice: "Pick one thing you've been forcing. Give it one week of simply trusting. Check in with how that feels.",
    affirmation: "My timing is perfect. Everything I need is already in motion.",
  },
  {
    id: "10",
    title: "Forgiveness",
    theme: "Setting Yourself Free",
    message: "Forgiveness is not for them. It is for you. It is laying down the weight of a story that has kept you small. You deserve to be free.",
    prompt: "Who ... or what ... are you ready to forgive?",
    reflection: "Is there something you haven't forgiven yourself for? What would compassion toward that version of you look like?",
    practice: "Write a forgiveness letter ... to someone else, or to yourself. You don't have to send it. The writing is the release.",
    affirmation: "I release the past and step into the freedom of the present.",
  },
  {
    id: "11",
    title: "Body",
    theme: "Coming Home to Your Body",
    message: "Your body has carried you through everything ... every heartbreak, every triumph, every ordinary day. She deserves to be thanked, not punished.",
    prompt: "How do you speak to your body when no one is listening?",
    reflection: "What would it feel like to be at peace with your body exactly as it is today?",
    practice: "Put your hands on a part of your body you've been critical of. Breathe. Say thank you.",
    affirmation: "I am grateful for my body. She is my home.",
  },
  {
    id: "12",
    title: "Ancestors",
    theme: "Inherited Strength",
    message: "You carry the prayers of women who came before you. Their resilience lives in your bones. You are not starting from nothing ... you are continuing something ancient.",
    prompt: "What strength have you inherited that you haven't yet claimed?",
    reflection: "Which women in your lineage inspire or move you, even if you never met them?",
    practice: "Light something fragrant. Speak the names of the women in your lineage ... biological or chosen. Thank them.",
    affirmation: "I am held by those who came before me. I carry their strength forward.",
  },
  {
    id: "13",
    title: "Intuition",
    theme: "Inner Knowing",
    message: "You have always known. The part of you that knew something was wrong, or right, before you could explain it ... that was never wrong. Trust her.",
    prompt: "What is your gut telling you that your head keeps overriding?",
    reflection: "Think of a time you ignored your intuition. What did that teach you about your own inner knowing?",
    practice: "Sit quietly. Ask yourself one question that's been on your mind. Notice the first answer that arises ... before the 'but.'",
    affirmation: "I trust my inner knowing. My intuition is my superpower.",
  },
  {
    id: "14",
    title: "Solitude",
    theme: "The Gift of Alone",
    message: "Solitude is not loneliness. It is how you learn the sound of your own voice beneath all the noise. In solitude, you remember what you actually think.",
    prompt: "When did you last spend time alone with yourself ... without your phone?",
    reflection: "Do you enjoy your own company? If not, what would make you someone you want to spend time with?",
    practice: "Spend 30 minutes today alone ... no screens, no tasks. Just you and your experience.",
    affirmation: "I enjoy my own company. I am whole on my own.",
  },
  {
    id: "15",
    title: "Courage",
    theme: "Sacred Bravery",
    message: "Courage is not the absence of fear. It is taking the next step while your heart pounds. You have been courageous so many times already. You can do it again.",
    prompt: "What one brave act has been calling to you?",
    reflection: "Look back at a moment you were afraid but moved forward anyway. What did that teach you about yourself?",
    practice: "Take one small step today toward something that scares you. Micro-courage counts.",
    affirmation: "I am braver than I know. I take one courageous step today.",
  },
  {
    id: "16",
    title: "Joy",
    theme: "Permission to Flourish",
    message: "Joy is not something you wait for until everything is settled. It is a daily practice ... a decision to let beauty land. You are allowed to be happy even now.",
    prompt: "What brings you joy that you've been postponing?",
    reflection: "Do you feel you've earned the right to be joyful? Where might that belief be limiting you?",
    practice: "Do one thing today purely for the joy of it. Notice how your body feels as you do it.",
    affirmation: "Joy is my birthright. I welcome it fully into my life.",
  },
  {
    id: "17",
    title: "Truth",
    theme: "Living Authentically",
    message: "The most exhausting thing is pretending. When you let the truth of who you are be seen ... even partially ... the weight lifts. Authenticity is rest.",
    prompt: "Where are you performing a version of yourself that isn't quite true?",
    reflection: "What parts of yourself do you hide, and who do you hide them from? What would happen if you stopped?",
    practice: "Share one authentic thing with someone today ... something real, not what you think they want to hear.",
    affirmation: "I am enough exactly as I am. My truth is safe here.",
  },
  {
    id: "18",
    title: "Play",
    theme: "The Forgotten Medicine",
    message: "You were not born serious. Play is not a reward for the responsible adult ... it is medicine. Let yourself be silly, creative, light. You need it.",
    prompt: "What did you love to do as a child that you've abandoned?",
    reflection: "What would it mean to bring more lightness into your everyday life ... without needing a reason?",
    practice: "Do something playful today. Dance. Draw. Blow bubbles. Let yourself be a little ridiculous.",
    affirmation: "I give myself permission to play. Lightness is part of my healing.",
  },
  {
    id: "19",
    title: "Stillness",
    theme: "The Power of Pause",
    message: "In the stillness between thoughts, you exist without labels, without roles, without history. You are simply here. This is your most natural state.",
    prompt: "When do you allow yourself to simply be still?",
    reflection: "What are you afraid might surface if you sat with yourself in silence?",
    practice: "Set a timer for five minutes. Sit. Do nothing. Notice what arises without trying to fix it.",
    affirmation: "In stillness, I find myself. I am at peace in the quiet.",
  },
  {
    id: "20",
    title: "Belonging",
    theme: "Finding Your People",
    message: "You are not too much. You are not too little. There are people who will love the specific, unusual, beautiful frequency of you. Don't shrink to fit smaller containers.",
    prompt: "Do you feel you truly belong somewhere? What does belonging feel like?",
    reflection: "Have you ever made yourself smaller to fit into a space that wasn't actually meant for you?",
    practice: "Reach out to one person who makes you feel genuinely seen. Tell them what they mean to you.",
    affirmation: "I belong to myself first. My people will find me as I become more fully me.",
  },
  {
    id: "21",
    title: "Creativity",
    theme: "Your Original Voice",
    message: "Creativity is not a talent given to the lucky few. It is a birthright. When you create ... in any form ... you participate in the fundamental act of being alive.",
    prompt: "What would you create if you knew no one would judge it?",
    reflection: "When did you start believing your creativity wasn't good enough ... and who told you that?",
    practice: "Make something today just for yourself. Write, draw, cook, arrange flowers. The making is the point.",
    affirmation: "I am a creative being. My expression is valuable.",
  },
  {
    id: "22",
    title: "Anger",
    theme: "Sacred Fire",
    message: "Your anger is not a flaw. It is a signal. It knows when something matters, when a line has been crossed, when you have been betrayed. Listen to it.",
    prompt: "What are you angry about that you haven't allowed yourself to acknowledge?",
    reflection: "How do you relate to your own anger ... do you suppress it, explode it, or use it wisely?",
    practice: "Write down what you're angry about without softening it. Let it be as fierce as it needs to be. Then decide what it's telling you.",
    affirmation: "My anger is information. I listen to it with respect.",
  },
  {
    id: "23",
    title: "Healing",
    theme: "The Ongoing Return",
    message: "Healing is not linear. It spirals. You revisit old wounds not because you failed, but because you are ready for another layer of freedom.",
    prompt: "What part of your healing is asking for attention right now?",
    reflection: "What does healing look like for you on an ordinary day... not a breakthrough day, just a regular one?",
    practice: "Choose one gentle act of healing today. A bath. A conversation. A good cry. Permission to not be okay.",
    affirmation: "I am healing in layers. Every step forward is enough.",
  },
  {
    id: "24",
    title: "Vision",
    theme: "Calling in What's Next",
    message: "You are allowed to want a life that looks different from the one you have. Dreaming is not irresponsible ... it is the beginning of becoming.",
    prompt: "What does your most authentic future look like?",
    reflection: "What vision for your life have you dismissed as unrealistic? What made it feel impossible?",
    practice: "Write or draw what your ideal life looks like ... not perfect, but true. Don't filter. Don't shrink.",
    affirmation: "I hold my vision with faith. What I dream of is possible.",
  },
  {
    id: "25",
    title: "Tenderness",
    theme: "Gentle Power",
    message: "You don't have to be hard to be strong. Tenderness is not weakness ... it is the kind of strength that endures, that heals, that connects.",
    prompt: "Where can you meet yourself with more tenderness today?",
    reflection: "Are you gentler with others than you are with yourself? What would it look like to turn that tenderness inward?",
    practice: "Speak to yourself today the way you would speak to someone you deeply love who is struggling.",
    affirmation: "I treat myself with the tenderness I deserve.",
  },
  {
    id: "26",
    title: "Seasons",
    theme: "Natural Cycles",
    message: "You are not meant to bloom all year. Winter is not failure. Fallow ground is not empty ... it is gathering itself for what comes next.",
    prompt: "What season are you in right now, and what does that season need?",
    reflection: "Have you been forcing spring when you're really in winter? What would honouring the season you're in look like?",
    practice: "Identify your current inner season ... spring, summer, autumn, or winter. Do one thing that honours it.",
    affirmation: "I trust my seasons. Every phase is part of my wholeness.",
  },
  {
    id: "27",
    title: "Receiving",
    theme: "Opening to Grace",
    message: "You are a generous giver. But giving from depletion is not virtue ... it is self-abandonment. Receiving is how you fill back up.",
    prompt: "How comfortable are you with receiving? What makes it hard?",
    reflection: "When someone offers you help, a compliment, or care ... what happens inside you? Is there resistance?",
    practice: "Accept one thing you're offered today without deflecting, minimizing, or immediately reciprocating. Just receive.",
    affirmation: "I am open to receiving. I allow goodness to flow into my life.",
  },
  {
    id: "28",
    title: "Presence",
    theme: "The Gift of Now",
    message: "The life you are waiting to live is already happening. Right now, in the ordinary moments, is where everything real takes place.",
    prompt: "Where in your life are you most absent? What are you thinking about instead of where you are?",
    reflection: "What would you notice if you were fully present for the next hour of your life?",
    practice: "Choose one ordinary activity today ... eating, walking, washing dishes ... and do it with complete presence.",
    affirmation: "I am here, now. This moment is enough.",
  },
  {
    id: "29",
    title: "Wilderness",
    theme: "The Unknown as Teacher",
    message: "There are times in life when the path disappears and you must walk on unmarked ground. This is not punishment. This is initiation.",
    prompt: "What unknown are you being asked to walk through?",
    reflection: "Looking back, what did your most uncertain periods ultimately teach you about yourself?",
    practice: "Make friends with one thing you don't know today. Sit with the question without grasping for an answer.",
    affirmation: "I trust myself in the unknown. I am guided even when the path isn't clear.",
  },
  {
    id: "30",
    title: "Mirrors",
    theme: "What Others Reflect",
    message: "The qualities you admire most in others already live in you, waiting to be cultivated. The qualities that trigger you most are invitations to look within.",
    prompt: "Who is mirroring something important to you right now?",
    reflection: "What do you most admire in others that you have difficulty claiming in yourself?",
    practice: "Name one quality you envy in someone else. Ask yourself: where does this quality live, in seed form, in me?",
    affirmation: "I see myself clearly. I reclaim the gifts I've admired in others.",
  },
  {
    id: "31",
    title: "Enough",
    theme: "Radical Sufficiency",
    message: "You have done enough today. You are enough today. Enoughness is not a milestone you reach ... it is a choice you make, right now, in this moment.",
    prompt: "What would shift if you genuinely believed you were enough?",
    reflection: "What is your internal benchmark for 'enough,' and who set that benchmark? Is it truly yours?",
    practice: "End today by listing three things you did that were enough. Not extraordinary ... just enough.",
    affirmation: "I am enough. What I have done today is enough.",
  },
  {
    id: "32",
    title: "Wildness",
    theme: "Untamed Nature",
    message: "There is a wild, untamed part of you that civilisation asked you to contain. She is not dangerous. She is alive. She knows things the domesticated version of you has forgotten.",
    prompt: "What part of your wildness have you been containing?",
    reflection: "What did you love doing that was messy, loud, or unconventional ... before you learned to be more 'proper'?",
    practice: "Do one wild thing today. Eat dessert first. Wear the unusual thing. Say the unexpected truth.",
    affirmation: "I embrace my wild nature. She is sacred and wise.",
  },
  {
    id: "33",
    title: "Devotion",
    theme: "What You Live For",
    message: "Devotion is what happens when you stop performing your life and start living it. What are you truly devoted to, beneath the roles and the obligations?",
    prompt: "What are you most deeply devoted to, when you're honest with yourself?",
    reflection: "Does your daily life reflect what you say matters most to you? Where is there alignment ... and where is there a gap?",
    practice: "Spend 20 minutes in service of your deepest devotion today. Let nothing interrupt it.",
    affirmation: "I live in alignment with what I truly value.",
  },
  {
    id: "34",
    title: "Shadow",
    theme: "Integrating the Dark",
    message: "The parts of yourself you've pushed into the dark are not broken. They are waiting to be understood. Wholeness includes everything ... light and shadow both.",
    prompt: "What part of yourself are you most ashamed of ... and what might it actually need?",
    reflection: "What do you most judge in others that might be a disowned part of yourself?",
    practice: "Sit with one of your 'darker' traits ... jealousy, pride, neediness ... without judgment. Ask it: what are you trying to protect?",
    affirmation: "I welcome all parts of myself. My wholeness includes my shadow.",
  },
  {
    id: "35",
    title: "Remembrance",
    theme: "Who You Were Before",
    message: "Before the world told you who to be, you already were someone. That child knew things. She carried seeds of your truest self. What did she love?",
    prompt: "Who were you before you learned to be what others needed you to be?",
    reflection: "What did you love, believe, or dream as a child that you've since abandoned? What happened to change that?",
    practice: "Look at a childhood photo. Write a letter to that version of yourself. Tell her what you've learned.",
    affirmation: "I remember who I am beneath all that I've been asked to be.",
  },
  {
    id: "36",
    title: "Nourishment",
    theme: "Filling the Well",
    message: "What genuinely feeds you ... your spirit, your mind, your body ... is not a luxury. It is the source. Without it, you give from debt.",
    prompt: "What truly nourishes you? Are you making time for it?",
    reflection: "What fills you up versus what merely distracts you? Can you feel the difference in your body?",
    practice: "Do one genuinely nourishing thing today. Not a task dressed as self-care. Something that genuinely restores.",
    affirmation: "I nourish myself with care. My cup is full.",
  },
  {
    id: "37",
    title: "Release",
    theme: "Letting Go",
    message: "Some things are finished. Not failed ... finished. Letting go is not giving up. It is making room for what is trying to begin.",
    prompt: "What is ready to be released from your life?",
    reflection: "What are you holding onto out of habit, fear, or loyalty that no longer serves your becoming?",
    practice: "Write one thing you're releasing on a piece of paper. Hold it, feel it, then let it go symbolically ... tear it, burn it, release it to water.",
    affirmation: "I release what is finished. I create space for what is becoming.",
  },
  {
    id: "38",
    title: "Feminine",
    theme: "Reclaiming the Sacred Feminine",
    message: "Feminine is not fragile. It is the force of life itself ... cyclical, generative, intuitive, vast. You carry this ancient power in your body.",
    prompt: "How do you feel about your femininity? What has shaped that relationship?",
    reflection: "Were you taught to see your feminine nature as weakness? What would it mean to see it as sacred power?",
    practice: "Do something that honours your feminine nature today ... in whatever way feels true to you.",
    affirmation: "My femininity is power. I reclaim it fully and with pride.",
  },
  {
    id: "39",
    title: "Truth-Teller",
    theme: "Prophetic Honesty",
    message: "Someone in your life needs to hear you speak your truth. Not cruelly ... but clearly, lovingly, without apology. The world needs women who say the true thing.",
    prompt: "What truth have you been swallowing in a relationship or situation?",
    reflection: "What stops you from speaking your truth? Is it fear of conflict, disapproval, or abandonment?",
    practice: "Practice saying your truth out loud alone. Just speaking it, even quietly, is a beginning.",
    affirmation: "I speak truth with love and clarity. My voice creates change.",
  },
  {
    id: "40",
    title: "Ceremony",
    theme: "Making the Ordinary Sacred",
    message: "When you mark your life with intention ... a candle, a breath, a moment of gratitude ... the ordinary becomes altar. Your life is worthy of ceremony.",
    prompt: "What ordinary moment could you ritualize to make it feel sacred?",
    reflection: "What rituals have you abandoned that used to bring you meaning? What made you stop?",
    practice: "Create a simple ceremony around something ordinary today. Make your morning tea with complete attention. Light a candle before dinner. Mark the moment.",
    affirmation: "I make my life sacred. Every moment is worthy of my full attention.",
  },
  {
    id: "41",
    title: "Abundance",
    theme: "Opening to More",
    message: "Abundance is not just money. It is time. Connection. Beauty. Peace. When you attune to what you already have, more of what you need can find its way to you.",
    prompt: "What abundance do you already have that you've been overlooking?",
    reflection: "Where do you operate from a scarcity mindset ... and is there evidence that contradicts that belief?",
    practice: "Write an abundance list ... ten things you have that you're grateful for. Reread it slowly.",
    affirmation: "I live in abundance. I notice and receive what is already here.",
  },
  {
    id: "42",
    title: "Trust",
    theme: "Faith in the Unfolding",
    message: "You have survived everything that came before this moment. Every hard season prepared you for something. You are being held, even when it doesn't feel like it.",
    prompt: "What do you need to trust right now that you've been resisting?",
    reflection: "Has life ever surprised you with an outcome better than what you'd planned or expected? What did that teach you?",
    practice: "Choose one thing to trust today ... in yourself, in others, in the process of your life. Let it rest.",
    affirmation: "I trust the unfolding of my life. I am supported.",
  },
  {
    id: "43",
    title: "Love",
    theme: "The Source",
    message: "Love is not a reward for being perfect. It is the ground beneath everything ... most essentially, beneath your relationship with yourself.",
    prompt: "How do you love yourself in action ... not just in concept?",
    reflection: "What does self-love actually look like in your daily life? Not bubble baths ... real self-love.",
    practice: "Do one act of genuine love for yourself today. Choose yourself. Protect yourself. Cherish yourself.",
    affirmation: "I am love. I lead my life from this source.",
  },
  {
    id: "44",
    title: "Becoming",
    theme: "The Ongoing Story",
    message: "You are not a finished thing. You are becoming. And this ... this messy, tender, courageous, ongoing becoming ... is the most beautiful thing you will ever do.",
    prompt: "Who are you becoming, and what does she need from you today?",
    reflection: "How have you changed in the last year? In the last five years? Are you becoming who you want to be?",
    practice: "Write a letter from your future self ... the woman you are becoming ... to the woman you are now. What does she want you to know?",
    affirmation: "I trust my becoming. Every step is sacred. I am exactly where I need to be.",
  },
];
